# Generated by Django 5.0.3 on 2026-06-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studmodel',
            old_name='emai',
            new_name='email',
        ),
    ]
